// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0lxYloQcbDw0NJf81WdA0RuR7tCajEHk',
    appId: '1:52875851411:web:8834e886a5fcf66ec4bf66',
    messagingSenderId: '52875851411',
    projectId: 'orderapp-21768',
    authDomain: 'orderapp-21768.firebaseapp.com',
    storageBucket: 'orderapp-21768.firebasestorage.app',
    measurementId: 'G-S2FBT52ENK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA70MMnWfjVlGSy6uuWqcmSHnVKp9vQhUg',
    appId: '1:52875851411:android:d307effc3d284777c4bf66',
    messagingSenderId: '52875851411',
    projectId: 'orderapp-21768',
    storageBucket: 'orderapp-21768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAniWrPxgHIPmPgN1RhTUwR20--rNikcLA',
    appId: '1:52875851411:ios:07a2d3f122dc2f0ec4bf66',
    messagingSenderId: '52875851411',
    projectId: 'orderapp-21768',
    storageBucket: 'orderapp-21768.firebasestorage.app',
    iosBundleId: 'com.test.orderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAniWrPxgHIPmPgN1RhTUwR20--rNikcLA',
    appId: '1:52875851411:ios:07a2d3f122dc2f0ec4bf66',
    messagingSenderId: '52875851411',
    projectId: 'orderapp-21768',
    storageBucket: 'orderapp-21768.firebasestorage.app',
    iosBundleId: 'com.test.orderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0lxYloQcbDw0NJf81WdA0RuR7tCajEHk',
    appId: '1:52875851411:web:176ebd47a94e4523c4bf66',
    messagingSenderId: '52875851411',
    projectId: 'orderapp-21768',
    authDomain: 'orderapp-21768.firebaseapp.com',
    storageBucket: 'orderapp-21768.firebasestorage.app',
    measurementId: 'G-V208JYBMYW',
  );
}
