// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBOP_bXx_FY-kS0wknUQluBDzIJJL2yA',
    appId: '1:570828303394:web:b2013da4795d3a59a3ae7b',
    messagingSenderId: '570828303394',
    projectId: 'finalexpense-5d331',
    authDomain: 'finalexpense-5d331.firebaseapp.com',
    storageBucket: 'finalexpense-5d331.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtIUAxwgohqGTU_pfcNCCemBdg9cd76pI',
    appId: '1:570828303394:android:dcadba8f80290d2aa3ae7b',
    messagingSenderId: '570828303394',
    projectId: 'finalexpense-5d331',
    storageBucket: 'finalexpense-5d331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrVrCTtwhkEC1gFd5MFJByueNFTHvj30',
    appId: '1:570828303394:ios:4d9df8c49b221f9aa3ae7b',
    messagingSenderId: '570828303394',
    projectId: 'finalexpense-5d331',
    storageBucket: 'finalexpense-5d331.firebasestorage.app',
    iosBundleId: 'com.expense.firstpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrVrCTtwhkEC1gFd5MFJByueNFTHvj30',
    appId: '1:570828303394:ios:4d9df8c49b221f9aa3ae7b',
    messagingSenderId: '570828303394',
    projectId: 'finalexpense-5d331',
    storageBucket: 'finalexpense-5d331.firebasestorage.app',
    iosBundleId: 'com.expense.firstpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBOP_bXx_FY-kS0wknUQluBDzIJJL2yA',
    appId: '1:570828303394:web:ee9fc60284730b83a3ae7b',
    messagingSenderId: '570828303394',
    projectId: 'finalexpense-5d331',
    authDomain: 'finalexpense-5d331.firebaseapp.com',
    storageBucket: 'finalexpense-5d331.firebasestorage.app',
  );
}
